/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as etnRewardsSol from "./ETNRewards.sol";
export type { etnRewardsSol };
export type { ETNMock } from "./ETNMock";
export type { FitChainNFT } from "./FitChainNFT";
export type { FitChainRewards } from "./FitChainRewards";
export type { Lock } from "./Lock";
